package com.elmayorista.notification;

public enum NotificationType {
    SALE_CREATED,
    SALE_PENDING_REMINDER,
    SALE_PENDING_ADMIN_ALERT,
    SALE_UNDER_REVIEW,
    FIADO_CREATED,
    CUSTOMER_REGISTERED,
    CUSTOMER_APPROVED,
    CUSTOMER_FIADO_CREATED,
    FIADO_APPROVED,
    FIADO_REJECTED,
    SALE_APPROVED,
    SALE_REJECTED,
    SALE_RETURNED,
    RANKING_ACHIEVEMENT
}
